### ISSUE TITLE
Add FooterComponent prop

### ISSUE THREAD

**Issue by mezalejandro** [chrizuuu/react-native-gallery-preview#6]
Hello, first thank you for this library is amazing.
Can you create a prop like HeaderComponent but to the footer?
In the footer for example I can add a text for the image.

Thank you so much,
Greetings

**Comment by krzysztofbonecki** [comment]
Hi, thank you for using my library.

I think I will try to add it at the end of this week

**Comment by chrizuuu** [comment]
Hi, just came out version 1.1.3. in which I added "OverlayComponent" props. OverlayComponent is no different from HeaderComponent but the name itself illustrates more what you can put in it. I also added an example with a footer so that it might make it easier for you to implement.

In the next releases I will probably also add "goNext" and "goPrev" methods which will allow, for example, to create physical buttons to move between photos

I didn't decide to create a typical FooterComponent, because from the beginning the idea was to make the library focus mainly on the photo interaction part, and leave the visual part, such as headers and footers, to developers who will use this library.

If you have any more questions go ahead ;)
